### ISSUE TITLE
How to find the "spyserver protocol" document

### ISSUE THREAD

**Issue by BlueRhino** [miweber67/spyserver_client#1]
Hello, I want to write a spyserver Python client, how to find the protocol documentation for spyserver

**Comment by kevinelliott** [comment]
@BlueRhino Any luck? I want the same.

**Comment by miweber67** [comment]
I am not aware that any such document exists. The closest you are going to get is the spyserver protocol header file. As far as for handling the state machine aspects; you can either port the code from C, or call the client as a subprocess.
