### ISSUE TITLE
Can not compile under Ubuntu 18.04.

### ISSUE THREAD

**Issue by ly2ss** [miweber67/spyserver_client#3]
Using:
gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1)
libsamplerate-0.1.9 

g++ -I. -O3 -Wall   -c -o ss_client.o ss_client.cc
ss_client.cc: In function ‘int main(int, char**)’:
ss_client.cc:523:62: error: invalid conversion from ‘const float*’ to ‘float*’ [-fpermissive]
                src_short_to_float_array ((int16_t*)buf, data.data_in, samps*2);
                                                         ~~~~~^~~~~~~
In file included from ss_client.cc:7:0:
/usr/local/include/samplerate.h:171:6: note:   initializing argument 2 of ‘void src_short_to_float_array(const short int*, float*, int)’
 void src_short_to_float_array (const short *in, float *out, int len) ;
      ^~~~~~~~~~~~~~~~~~~~~~~~
<builtin>: recipe for target 'ss_client.o' failed
make: *** [ss_client.o] Error 1

**Comment by miweber67** [comment]
I don't have that system, compiler, or libsamplerate version, but my investigation of the code suggests that the change I commited in ee20bca should fix that problem. Please try it and report back? If it does not solve the problem if you have a solution / pull request let me know.

**Comment by ly2ss** [comment]
Compiled ok. Thanks!

**Comment by miweber67** [comment]
Awesome, thanks. :-)
